# Generated by Django 2.2.7 on 2019-11-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название продукта')),
                ('photo', models.ImageField(upload_to='media/common/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleRU', models.CharField(blank=True, default='Без названия', max_length=256, null=True, verbose_name='Название продукта')),
                ('titleUZ', models.CharField(blank=True, default='Без названия', max_length=256, null=True, verbose_name='Название продукта')),
                ('photo', models.ImageField(upload_to='media/products/', verbose_name='Фото')),
                ('descriptionRU', models.TextField(verbose_name='Описание на русском')),
                ('descriptionUZ', models.TextField(verbose_name='Описание на узбекском')),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
                ('category', models.ManyToManyField(to='main.Category')),
                ('volume', models.ManyToManyField(to='main.ProductVolume')),
            ],
        ),
        migrations.CreateModel(
            name='PriceForVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default='0', verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductVolume')),
            ],
        ),
    ]
