# Generated by Django 2.2.7 on 2019-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='priceforvolume',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productvolume',
            options={'verbose_name': 'Объём продукции', 'verbose_name_plural': 'Объёмы продукции'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='titleRU',
            field=models.CharField(default='Без названия', max_length=256, verbose_name='Название категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='titleUZ',
            field=models.CharField(default='Без названия', max_length=256, verbose_name='Название категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название фото'),
        ),
        migrations.AlterField(
            model_name='productvolume',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название единицы объёма'),
        ),
    ]
