# Generated by Django 2.2.7 on 2019-11-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191107_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='titleRU',
            field=models.CharField(max_length=256, verbose_name='Название категории RU'),
        ),
        migrations.AlterField(
            model_name='category',
            name='titleUZ',
            field=models.CharField(max_length=256, verbose_name='Название категории UZ'),
        ),
        migrations.AlterField(
            model_name='priceforvolume',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='priceforvolume',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductVolume', verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='main.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='titleRU',
            field=models.CharField(blank=True, default='Без названия', max_length=256, null=True, verbose_name='Название продукта RU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='titleUZ',
            field=models.CharField(blank=True, default='Без названия', max_length=256, null=True, verbose_name='Название продукта UZ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.ManyToManyField(to='main.ProductVolume', verbose_name='Объём'),
        ),
    ]
