# Generated by Django 2.2.7 on 2019-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191111_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ManyToManyField(to='main.Photo'),
        ),
    ]
