# Generated by Django 2.2.7 on 2019-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191115_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Без названия', max_length=256, null=True, verbose_name='Название бренда')),
            ],
        ),
    ]
