# Generated by Django 2.2.7 on 2019-11-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
    ]
