# Generated by Django 2.2.7 on 2019-11-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191124_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Без названия', max_length=256, null=True, verbose_name='Название бренда')),
                ('picture', models.ImageField(upload_to='media/optionPictures/', verbose_name='Пиктограмма')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ManyToManyField(to='main.Photo', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='FreeOptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Без названия', max_length=256, null=True, verbose_name='Название бренда')),
                ('options', models.ManyToManyField(to='main.FreeOption', verbose_name='Список опций')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(to='main.FreeOptionGroup', verbose_name='Опции'),
        ),
    ]
