# Generated by Django 2.2.7 on 2019-11-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191128_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeoptiongroup',
            options={'verbose_name': 'Группа опций', 'verbose_name_plural': 'Группы опций'},
        ),
    ]
