# Generated by Django 2.2.7 on 2019-11-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191129_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceforoption',
            old_name='volume',
            new_name='option',
        ),
        migrations.DeleteModel(
            name='PriceForVolume',
        ),
        migrations.DeleteModel(
            name='ProductVolume',
        ),
    ]
