# Generated by Django 2.2.7 on 2019-11-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191129_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeoptiongroup',
            name='options',
            field=models.ManyToManyField(blank=True, to='main.FreeOption', verbose_name='Список опций'),
        ),
    ]
