# Generated by Django 2.2.7 on 2019-12-02 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191129_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
            options={
                'verbose_name': 'Временный продукт',
                'verbose_name_plural': 'Временные продукты',
            },
        ),
        migrations.CreateModel(
            name='TempOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default='Без названия', max_length=1024, null=True, verbose_name='Имя')),
                ('lastName', models.CharField(blank=True, default='Без названия', max_length=1024, null=True, verbose_name='Имя')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('cashOrCard', models.BooleanField(default=False, verbose_name='Оплата пластиком')),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата приобретения билета')),
                ('products', models.ManyToManyField(to='main.TempProduct')),
            ],
            options={
                'verbose_name': 'Временный заказ',
                'verbose_name_plural': 'Временные заказы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата приобретения билета')),
                ('tempOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TempOrder')),
            ],
            options={
                'verbose_name': 'Временный заказ',
                'verbose_name_plural': 'Временные заказы',
            },
        ),
    ]
