# Generated by Django 2.2.7 on 2019-12-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_temporder_tempproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('products', models.ManyToManyField(to='main.TempProduct')),
            ],
            options={
                'verbose_name': 'Временный заказ',
                'verbose_name_plural': 'Временные заказы',
            },
        ),
    ]
