# Generated by Django 2.2.7 on 2019-12-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20191202_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempproduct',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.FreeOption'),
        ),
        migrations.AddField(
            model_name='tempproduct',
            name='optionGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.FreeOptionGroup'),
        ),
    ]
