# Generated by Django 2.2.7 on 2019-12-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20191202_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempproduct',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
