# Generated by Django 2.2.7 on 2019-12-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_tempproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporder',
            name='cashOrCard',
        ),
        migrations.AddField(
            model_name='temporder',
            name='phone',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер телефона'),
        ),
    ]
