# Generated by Django 2.2.7 on 2019-12-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20191204_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название группы категорий')),
                ('categoies', models.ManyToManyField(to='main.Category')),
            ],
            options={
                'verbose_name': 'Группа категорий',
                'verbose_name_plural': 'Группы категорий',
            },
        ),
    ]
