# Generated by Django 2.2.7 on 2019-12-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_groupcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='titleRU',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='titleRU',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='titleUZ',
        ),
        migrations.RemoveField(
            model_name='product',
            name='descriptionUZ',
        ),
        migrations.RemoveField(
            model_name='product',
            name='titleUZ',
        ),
    ]
