# Generated by Django 2.2.7 on 2019-12-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20191206_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='photo',
            field=models.ImageField(default=None, upload_to='media/brandPricture/', verbose_name='Пиктограмма'),
            preserve_default=False,
        ),
    ]
