# Generated by Django 2.2.7 on 2019-12-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_brand_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subCat',
            field=models.ManyToManyField(blank=True, related_name='_category_subCat_+', to='main.Category'),
        ),
    ]
