# Generated by Django 2.2.7 on 2019-12-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_category_subcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название фото')),
                ('photo', models.ImageField(upload_to='media/common/', verbose_name='Фото')),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Фото для баннеров',
                'verbose_name_plural': 'Фото для баннеров',
            },
        ),
    ]
