# Generated by Django 2.2.7 on 2019-12-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_bannerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerphoto',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Краткое описание'),
        ),
    ]
